ALTER TABLE recipes
    ADD COLUMN IF NOT EXISTS ingredient_strings JSONB DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS instructions JSONB DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS note TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS liked BOOLEAN DEFAULT FALSE;
